### PR TITLE
fix missing com.qualcomm.location

### PR DESCRIPTION
**Pull request by ygorigor**

### CODE REVIEW

**Comment by ygorigor** [comment]
com.qualcomm.location.apk from garlic bootloop the phone

**Comment by ygorigor** [comment]
I leave this open for now till my other pull request will be merged

**Comment by ygorigor** [comment]
@danielstuart14 should I close this?

**Comment by danielstuart14** [comment]
Let this open for now, I'm trying to address that.
Once we get a blob that work, I'll merge this.

**Comment by ygorigor** [comment]
Ok

**Comment by ygorigor** [comment]
Maybe blob from Nokia 6 will work.

**Comment by danielstuart14** [comment]
cherry-picked. 
Let's see if it works.

**Pull request closed without merging**
